const CommentsActionTypes = {
    FETCH_COMMENTS_START: "FETCH_COMMENTS_START",
    FETCH_PARENT_COMMENTS_SUCCESS: "FETCH_PARENT_COMMENTS_SUCCESS",
    FETCH_CHILD_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS"
}
export default CommentsActionTypes