const CommentsActionTypes = {
    FETCH_COMMENTS_START: "FETCH_COMMENTS_START",
    FETCH_PARENT_COMMENTS_SUCCESS: "FETCH_PARENT_COMMENTS_SUCCESS",
    FETCH_CHILD_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
    FETCH_CHILD_COMMENTS_SUCCESS: "FETCH_CHILD_COMMENTS_SUCCESS",
    SET_COMMENTS_TO_INITIAL_STATE: "SET_COMMENTS_TO_INITIAL_STATE"
}
export default CommentsActionTypes