const StoriesActionTypes = {
    FETCH_COLLECTIONS_START_CALL: 'FETCH_COLLECTIONS_START_CALL',
    SET_INITIAL_IDS: 'SET_INITIAL_IDS',
    FETCH_STORIES_SUCCESS: 'FETCH_STORIES_SUCCESS',
    FETCH_SINGLE_STORIE: 'FETCH_SINGLE_STORIE',
}
export default StoriesActionTypes 